language: "php"

addons:
  mariadb: '10.0'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
  include:
    - php: 7.1
      env:
        - EXECUTE_COVERAGE=true
    - php: nightly
    - php: hhvm

before_script:
  - wget http://downloads.mysql.com/docs/sakila-db.tar.gz
  - tar xvf sakila-db.tar.gz
  - mysql < sakila-db/sakila-schema.sql -uroot
  - mysql < sakila-db/sakila-data.sql -uroot
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer install

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover ; fi
