language: "php"

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - "composer install"

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover --access-token="630d2c3a5740809a24244c0774b6e9dc73aad4b42fa6ac4499062918215dd567"
